name: Publish
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Download Dalamud
      run: |
        curl -o latest.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
        unzip latest.zip -d ~/dalamud/
    - name: Build
      run: dotnet build --configuration Release -p:IsCI=true /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release -p:IsCI=true /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack --configuration Release -p:IsCI=true /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push FlexConfig.${VERSION}.nupkg --skip-duplicate --no-symbols --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
      
      
      
      
